- task: IISWebAppManagementOnMachineGroup@0
  inputs:
    IISDeploymentType: 'IISWebsite'
    ActionIISWebsite: 'CreateOrUpdateWebsite'
    WebsiteName: 'asd'
    WebsitePhysicalPath: '%SystemDrive%\inetpub\wwwroot'
    WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
    DotNetVersionForWebsite: 'v4.0'
    PipeLineModeForWebsite: 'Integrated'
    AppPoolIdentityForWebsite: 'ApplicationPoolIdentity'
    PhysicalPathForVD: '%SystemDrive%\inetpub\wwwroot'
    PhysicalPathForApplication: '%SystemDrive%\inetpub\wwwroot'
    DotNetVersionForApplication: 'v4.0'
    PipeLineModeForApplication: 'Integrated'
    AppPoolIdentityForApplication: 'ApplicationPoolIdentity'
    DotNetVersion: 'v4.0'
    PipeLineMode: 'Integrated'
    AppPoolIdentity: 'ApplicationPoolIdentity'


# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: false
- task: PublishBuildArtifacts@1
